spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/marketing?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=utf8
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: local-secret-key-must-be-at-least-32-chars-long
  expiration-in-ms: 86400000

elice:
  api-url: ${INVENTORY_API_URL:http://localhost:8000}
  api-key: ${INVENTORY_API_KEY:dummy-key}

kakao:
  api-key: be4784acd9547a84c372e98dc8878f53

server:
  port: 8080
